version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
      PGDATA: /data/postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./backup:/pgbackup
    networks:
      - postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@user.com
      PGADMIN_DEFAULT_PASSWORD: testuser
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on: 
      - postgres
    networks:
      - postgres

networks:
  postgres:

volumes:
    postgres:
    pgadmin: